name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Start Docker service
      run: |
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Build Docker image
      run: |
        docker build -t nttung245/flask_app:2 .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: nttung245
        password: Nguyenthanhtung245

    - name: Push Docker image
      run: |
        docker push nttung245/flask_app:2

  deploy:
    runs-on: ubuntu-22.04
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubeconfig
      run: |
        sudo swapoff -a
        sudo sed -i '/ swap / s/^/#/' /etc/fstab
        sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl
        sudo curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        sudo apt-get update

    - name: Install and set up kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        sudo apt-get update
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
        minikube start
        minikube node add

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s-deployment.yaml                                                                                      
